M48
; DRILL file {KiCad 7.0.5-0} date 2023 October 01, Sunday 21:30:40
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-01T21:30:40-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X3.2031Y-2.4543
X3.2031Y-4.4228
X6.4709Y-2.4543
X6.4709Y-4.4228
T0
M30
